# Generated by Django 4.1.7 on 2023-03-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to="images"),
        ),
    ]
