# Generated by Django 4.1.7 on 2023-03-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="modifiedDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="publishedDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
