# Generated by Django 4.1.7 on 2023-03-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_post_lat_post_lng"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="Lat",
            new_name="lat",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="Lng",
            new_name="lng",
        ),
    ]
