# Generated by Django 4.1.7 on 2023-03-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_rename_lat_post_lat_rename_lng_post_lng"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postname", models.CharField(max_length=70)),
                ("contents", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, default="", upload_to="images"),
                ),
            ],
        ),
    ]
